"""baseline_production_schema

Revision ID: a9c7df9f7190
Revises: 
Create Date: 2026-09-22 21:31:37.622235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c7df9f7190'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_station_aliases_alias'), table_name='station_aliases')
    op.drop_index(op.f('ix_station_aliases_id'), table_name='station_aliases')
    op.drop_index(op.f('ix_station_aliases_normalized_alias'), table_name='station_aliases')
    op.drop_index(op.f('ix_station_aliases_station_id'), table_name='station_aliases')
    op.drop_table('station_aliases')
    op.alter_column('coordinated_block_plans', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_coordinated_block_plans_id'), 'coordinated_block_plans', ['id'], unique=False)
    op.create_index(op.f('ix_coordinated_block_plans_plan_code'), 'coordinated_block_plans', ['plan_code'], unique=True)
    op.alter_column('corridors', 'zone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_corridors_prototype_code'), 'corridors', ['prototype_code'], unique=False)
    op.alter_column('execution_records', 'plan_job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'execution_records', 'maintenance_jobs', ['job_id'], ['id'])
    op.create_index(op.f('ix_maintenance_jobs_coordinated_plan_id'), 'maintenance_jobs', ['coordinated_plan_id'], unique=False)
    op.create_index(op.f('ix_maintenance_jobs_corridor_id'), 'maintenance_jobs', ['corridor_id'], unique=False)
    op.create_foreign_key(None, 'maintenance_jobs', 'corridors', ['corridor_id'], ['id'])
    op.drop_column('maintenance_jobs', 'rejection_reason')
    op.drop_column('stations', 'is_active')
    op.drop_column('stations', 'last_verified')
    op.drop_column('stations', 'source')
    op.drop_column('stations', 'category')
    op.drop_column('stations', 'source_version')
    op.drop_column('stations', 'district')
    op.drop_column('stations', 'normalized_name')
    op.drop_column('stations', 'state')
    op.drop_column('stations', 'normalized_code')
    op.alter_column('train_route_stops', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_train_route_stops_train_number'), table_name='train_route_stops')
    op.create_index(op.f('ix_train_route_stops_id'), 'train_route_stops', ['id'], unique=False)
    op.alter_column('trains', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_trains_id'), 'trains', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trains_id'), table_name='trains')
    op.alter_column('trains', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_train_route_stops_id'), table_name='train_route_stops')
    op.create_index(op.f('ix_train_route_stops_train_number'), 'train_route_stops', ['train_number'], unique=False)
    op.alter_column('train_route_stops', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('stations', sa.Column('normalized_code', sa.VARCHAR(length=15), nullable=True))
    op.add_column('stations', sa.Column('state', sa.VARCHAR(length=50), server_default=sa.text("'Tamil Nadu'"), nullable=True))
    op.add_column('stations', sa.Column('normalized_name', sa.VARCHAR(length=150), nullable=True))
    op.add_column('stations', sa.Column('district', sa.VARCHAR(length=100), nullable=True))
    op.add_column('stations', sa.Column('source_version', sa.VARCHAR(length=50), server_default=sa.text("'01.04.2025'"), nullable=True))
    op.add_column('stations', sa.Column('category', sa.VARCHAR(length=20), nullable=True))
    op.add_column('stations', sa.Column('source', sa.VARCHAR(length=100), server_default=sa.text("'Southern Railway'"), nullable=True))
    op.add_column('stations', sa.Column('last_verified', sa.DATETIME(), nullable=True))
    op.add_column('stations', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))
    op.add_column('maintenance_jobs', sa.Column('rejection_reason', sa.TEXT(), nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'maintenance_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_maintenance_jobs_corridor_id'), table_name='maintenance_jobs')
    op.drop_index(op.f('ix_maintenance_jobs_coordinated_plan_id'), table_name='maintenance_jobs')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'execution_records', type_='foreignkey')
    op.alter_column('execution_records', 'plan_job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_corridors_prototype_code'), table_name='corridors')
    op.alter_column('corridors', 'zone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_coordinated_block_plans_plan_code'), table_name='coordinated_block_plans')
    op.drop_index(op.f('ix_coordinated_block_plans_id'), table_name='coordinated_block_plans')
    op.alter_column('coordinated_block_plans', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('station_aliases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('station_id', sa.INTEGER(), nullable=False),
    sa.Column('alias', sa.VARCHAR(length=100), nullable=False),
    sa.Column('normalized_alias', sa.VARCHAR(length=100), nullable=False),
    sa.Column('alias_type', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['railway_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_aliases_station_id'), 'station_aliases', ['station_id'], unique=False)
    op.create_index(op.f('ix_station_aliases_normalized_alias'), 'station_aliases', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_station_aliases_id'), 'station_aliases', ['id'], unique=False)
    op.create_index(op.f('ix_station_aliases_alias'), 'station_aliases', ['alias'], unique=False)
    # ### end Alembic commands ###
